authors:
  annevanrossum:
    display_name: Anne van Rossum
    gravatar: 818dc2df03cd2f1ca7d6e6e701052f0c
    email: anne@dobots.nl
    web: http://www.annevanrossum.nl
    twitter: annevanrossum
    github: mrquincle

  laurensbliek:
    display_name: Laurens Bliek

  remcotukker:
    display_name: Remco Tukker


