authors:
  annevanrossum:
    display_name: Anne van Rossum
    gravatar: 818dc2df03cd2f1ca7d6e6e701052f0c
    email: anne@dobots.nl
    web: http://www.annevanrossum.nl
    twitter: annevanrossum
    github: mrquincle

  laurensbliek:
    display_name: Laurens Bliek

  remcotukker:
    display_name: Remco Tukker

  jannyramakers:
    display_name: Janny Ramakers

  marchulscher:
    display_name: Marc Hulscher

  bartvanvliet:
    display_name: Bart van Vliet

  dominikegger:
    display_name: Dominik Egger

  roemervlasveld:
    display_name: Roemer Vlasveld

  behnazshirmohamadi:
    display_name: Behnaz Shirmohamadi

  peetvantooren:
    display_name: Peet van Tooren
